### ISSUE TITLE
protocol and cipher configurations

### ISSUE THREAD

**Issue by icing** [abetterinternet/mod_tls#1]
There is discussion [here](https://github.com/abetterinternet/crustls/issues/58) and [here](https://github.com/ctz/rustls/issues/549) about the capabilities exposed by `rustls` and its C-API `crustls` about the specifications of TLS cipher suites. If such configuration options will be part of the API, the question is what `mod_tls` will do with them.

**protocols** 

Regarding tls protocol configuration, I'd like to follow [curl](https://github.com/curl/curl)'s approach of specifying the *minimum* version of the protocol to use. This means that only 2 possible configurations will exist for now:

```
TLSProtocol v1.2+
TLSProtocol v1.3+
```

The consequence is that if the next tls protocol version becomes added to `rustls`, it would be enabled on existing configurations. It also means that should TLSv1.2 become obsolete, neither configuration would prevent the server from running. But it would log a warning in the first case that v1.2 is no longer available.

The intention is to allow TLS protocols to evolve and become installed on a system (as in a shared library) without being blocked by copy&paste configurations for installed applications.

**ciphers**

For tls cipher configuration, a similar approach should be taken. If a new cipher is added or an existing one removed, the TLS of the server should continue to function and not break because one of the configured cipher strings is no longer available. And a new cipher, which has presumably been added for benefit, should become available. It is the responsibility of the `rustls` library to support ciphers suitable for use on the internet and the responsibility of a OS distribution to include the `(c)rustls` version suitable for that distribution.

Most users of an Apache server should have no need to configure anything about cipher suites in `mod_tls`, unless there is a need to select the *better* one amongst compatible suites. The decisions what is *better* needs to be made for the concrete setups, by the server administrator.

The idea is to offer configuration options that influence the *preference* of which cipher suite is used when a connection is negotiated with a client:

```
TLSCipherPreference TLS_CHACHA20_POLY1305_SHA256
TLSCipherPreference ECDHE-ECDSA-AES256-GCM-SHA384:TLS_AES_256_GCM_SHA384
```

This would mean "prefer these ciphers in the order given" when negotiating with a client. All other ciphers supported by `rustls` would remain to be available, but with less preference. If rustls adds a cipher, it will be usable. If rustls drops a cipher, the configuration will continue to work, logging a warning that (part of) the preference configuration will no longer have an effect.

/cc @jsha @djc @notroj

**Comment by covener** [comment]
> This would mean "prefer these ciphers in the order given" when negotiating with a client. All other ciphers supported by rustls would remain to be available, but with less preference. If rustls adds a cipher, it will be usable.

Is this wise with the vuln scanner industrial complex?  Maybe you could support a `-` prefix to really remove a cipher?

**Comment by JBlond** [comment]
> Is this wise with the vuln scanner industrial complex? Maybe you could support a - prefix to really remove a cipher?
SSLCipherSuite uses ! to negate. A - prefix might lead to confusion, also some cipher names contain a -

**Comment by icing** [comment]
@covener I think your concern is valid. Sites need a way to disable a cipher, for example right away in case of troubles, until ssl implementors can make new releases. Even if this would go very fast and only take a day.

@JBlond, good point. I am considering something like

```
TLSCiphersPrefer  name((:|\s+)name)*
TLSCiphersSuppress  name((:|\s+)name)*
```

Settable on a server or per virtual host, non-additive, e.g. each use would replace any previous definition. Suppression supersedes preference, irregardless of order.

**Comment by icing** [comment]
Implemented as specified. Test cases added for client/server settings and negotiations.

The naming of ciphers is now done according to the names appearing in the [IANA registry](https://www.iana.org/assignments/tls-parameters/tls-parameters.xhtml#tls-parameters-4). The only exception currently are the TLSv1.3 ciphers which are prefixed as `TLS13_`instead of just `TLS_`, as `rustls` does it in its internal instance definitions.

I think those will serve, but if anyone has an opinion, I am listening.
