### ISSUE TITLE
OCSP stapling and infrastructure

### ISSUE THREAD

**Issue by icing** [abetterinternet/mod_tls#4]
Collection of thoughts:

Apache has 2 OCSP Stapling implementations: the `mod_ssl` internal one and the recent one provided by `mod_md`. The basic mechanism now is `mod_ssl` asking around: "Is anyone willing to provide stapling for this `X509* cert` and `X509* issuer`?" and "I have a new connection, what is the current stapling DER for `X509* cert`?

If configured, `mod_md` answers both questions. On the first one, it adds that certificate to its OCSP supervision,  on the second one, it provides the current value it has retrieved from the responder. The supervision fetches and refreshes this DER data when necessary (missing or soon expiring).

With `mod_tls` we no longer want to pass around OpenSSL`s `X509*` certificate representations. Information passed needs to be ignorant of the SSL implementation used. In pseudo code, the 2 questions above can be implemented as:

```
typedef struct {
  unsigned char *data
  size_t len;
} bytes_t;

/**
 * Asking for someone to provide stapling for the cert (and included chain certs) in the PEM data.
 * @param id    opaque data uniquely identifying the certificate, provided by caller
 * @param pem   PEM data of certificate first, followed by chain certs, at least the issuer
 * @param s   the server being configured
 * @params p  a memory pool to use
 * @return != 0 iff stapling is being provided
 */
int ocsp_stapling_prime(const bytes_t *id, const bytes_t *pem, server_rec *s, apr_pool_t *p);

/**
 * Asking for OCSP response DER data for a certificate.
 * @param id    opaque data uniquely identifying the certificate, provided by caller
 * @param c the connection
 * @param s the SNI selected server of the connection
 * @param resp  writable buffer which can keep resp->len bytes
 * @param presp_len  number of bytes copied into resp
 * @return != 0 if OCSP data has been provided
 */
int ocsp_stapling_get_der(const bytes_t *id, conn_rec *c, server_rec *s, bytes_t *resp, *presp_len);

```
The first function is called during server startup/reload and is not time critical. Parsing the PEM data a second time should be an acceptable overhead. Should the same certificate be used several times in the server, the `id` should be the same and the parsing needs only be done once.

The second function will be called for each new connection. The `id` allows a fast lookup into a `hashmap` (or whatever the implementing module uses) and the OCSP response data is rather small, so copying into a caller provided buffer avoids lifetime/ownership issues.

The `id` exposed here can be chosen by the SSL module, but to work best it needs to be constant for a certificate, not depending on date/time or internal order of things. `mod_ssl` uses already a `SHA-1` digest of the certificate DER data internally and that should work here as well.

**Comment by jsha** [comment]
One possibility would be for `ocsp_stapling_prime` to return a "handle" for subsequent `ocsp_stapling_get_der` calls. Rather than `bytes_t`, that handle could be an integer (like an FD). That would mean we don't have to do any hashing, and the SSL modules can choose their own schemes for assignment. And it would presumably be a little faster to look up an integer than a (somewhat longer) hash.

**Comment by icing** [comment]
That is correct. The drawback would be that there can only be one OCSP providing implementation or the integers would have to be globally assigned. This is not theoretical, since apache currently has 2 active ones, depending on configuration. A matter of backward compatibility in a long release line.

**Comment by icing** [comment]
In apache httpd 2.4.48 the support for generic OCSP response infrastructure is present (and used by mod_ssl and mod_tls). Closing this.
